// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/example/dipoareoye/bluetoothframework/proto/hockey.proto

package com.example.dipoareoye.bluetoothframework.proto;

public final class GameStateProto {
  private GameStateProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GameStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GameState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 posX = 1;</code>
     */
    boolean hasPosX();
    /**
     * <code>optional int32 posX = 1;</code>
     */
    int getPosX();

    /**
     * <code>optional int32 VectorX = 2;</code>
     */
    boolean hasVectorX();
    /**
     * <code>optional int32 VectorX = 2;</code>
     */
    int getVectorX();

    /**
     * <code>optional int32 VectorY = 3;</code>
     */
    boolean hasVectorY();
    /**
     * <code>optional int32 VectorY = 3;</code>
     */
    int getVectorY();

    /**
     * <code>required .GameState.MessageType type = 4;</code>
     */
    boolean hasType();
    /**
     * <code>required .GameState.MessageType type = 4;</code>
     */
    com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState.MessageType getType();
  }
  /**
   * Protobuf type {@code GameState}
   */
  public static final class GameState extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:GameState)
      GameStateOrBuilder {
    // Use GameState.newBuilder() to construct.
    private GameState(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GameState(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GameState defaultInstance;
    public static GameState getDefaultInstance() {
      return defaultInstance;
    }

    public GameState getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GameState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              posX_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              vectorX_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              vectorY_ = input.readInt32();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState.MessageType value = com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                type_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.dipoareoye.bluetoothframework.proto.GameStateProto.internal_static_GameState_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.dipoareoye.bluetoothframework.proto.GameStateProto.internal_static_GameState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState.class, com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState.Builder.class);
    }

    public static com.google.protobuf.Parser<GameState> PARSER =
        new com.google.protobuf.AbstractParser<GameState>() {
      public GameState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameState(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GameState> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code GameState.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PUCK = 0;</code>
       */
      PUCK(0, 0),
      /**
       * <code>SCORE = 1;</code>
       */
      SCORE(1, 1),
      ;

      /**
       * <code>PUCK = 0;</code>
       */
      public static final int PUCK_VALUE = 0;
      /**
       * <code>SCORE = 1;</code>
       */
      public static final int SCORE_VALUE = 1;


      public final int getNumber() { return value; }

      public static MessageType valueOf(int value) {
        switch (value) {
          case 0: return PUCK;
          case 1: return SCORE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:GameState.MessageType)
    }

    private int bitField0_;
    public static final int POSX_FIELD_NUMBER = 1;
    private int posX_;
    /**
     * <code>optional int32 posX = 1;</code>
     */
    public boolean hasPosX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 posX = 1;</code>
     */
    public int getPosX() {
      return posX_;
    }

    public static final int VECTORX_FIELD_NUMBER = 2;
    private int vectorX_;
    /**
     * <code>optional int32 VectorX = 2;</code>
     */
    public boolean hasVectorX() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 VectorX = 2;</code>
     */
    public int getVectorX() {
      return vectorX_;
    }

    public static final int VECTORY_FIELD_NUMBER = 3;
    private int vectorY_;
    /**
     * <code>optional int32 VectorY = 3;</code>
     */
    public boolean hasVectorY() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 VectorY = 3;</code>
     */
    public int getVectorY() {
      return vectorY_;
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState.MessageType type_;
    /**
     * <code>required .GameState.MessageType type = 4;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required .GameState.MessageType type = 4;</code>
     */
    public com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState.MessageType getType() {
      return type_;
    }

    private void initFields() {
      posX_ = 0;
      vectorX_ = 0;
      vectorY_ = 0;
      type_ = com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState.MessageType.PUCK;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, posX_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, vectorX_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, vectorY_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, type_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, posX_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, vectorX_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, vectorY_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GameState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GameState)
        com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.dipoareoye.bluetoothframework.proto.GameStateProto.internal_static_GameState_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.dipoareoye.bluetoothframework.proto.GameStateProto.internal_static_GameState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState.class, com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState.Builder.class);
      }

      // Construct using com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        posX_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        vectorX_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        vectorY_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState.MessageType.PUCK;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.dipoareoye.bluetoothframework.proto.GameStateProto.internal_static_GameState_descriptor;
      }

      public com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState getDefaultInstanceForType() {
        return com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState.getDefaultInstance();
      }

      public com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState build() {
        com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState buildPartial() {
        com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState result = new com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.posX_ = posX_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.vectorX_ = vectorX_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.vectorY_ = vectorY_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState) {
          return mergeFrom((com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState other) {
        if (other == com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState.getDefaultInstance()) return this;
        if (other.hasPosX()) {
          setPosX(other.getPosX());
        }
        if (other.hasVectorX()) {
          setVectorX(other.getVectorX());
        }
        if (other.hasVectorY()) {
          setVectorY(other.getVectorY());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int posX_ ;
      /**
       * <code>optional int32 posX = 1;</code>
       */
      public boolean hasPosX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 posX = 1;</code>
       */
      public int getPosX() {
        return posX_;
      }
      /**
       * <code>optional int32 posX = 1;</code>
       */
      public Builder setPosX(int value) {
        bitField0_ |= 0x00000001;
        posX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 posX = 1;</code>
       */
      public Builder clearPosX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        posX_ = 0;
        onChanged();
        return this;
      }

      private int vectorX_ ;
      /**
       * <code>optional int32 VectorX = 2;</code>
       */
      public boolean hasVectorX() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 VectorX = 2;</code>
       */
      public int getVectorX() {
        return vectorX_;
      }
      /**
       * <code>optional int32 VectorX = 2;</code>
       */
      public Builder setVectorX(int value) {
        bitField0_ |= 0x00000002;
        vectorX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 VectorX = 2;</code>
       */
      public Builder clearVectorX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        vectorX_ = 0;
        onChanged();
        return this;
      }

      private int vectorY_ ;
      /**
       * <code>optional int32 VectorY = 3;</code>
       */
      public boolean hasVectorY() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 VectorY = 3;</code>
       */
      public int getVectorY() {
        return vectorY_;
      }
      /**
       * <code>optional int32 VectorY = 3;</code>
       */
      public Builder setVectorY(int value) {
        bitField0_ |= 0x00000004;
        vectorY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 VectorY = 3;</code>
       */
      public Builder clearVectorY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        vectorY_ = 0;
        onChanged();
        return this;
      }

      private com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState.MessageType type_ = com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState.MessageType.PUCK;
      /**
       * <code>required .GameState.MessageType type = 4;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required .GameState.MessageType type = 4;</code>
       */
      public com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState.MessageType getType() {
        return type_;
      }
      /**
       * <code>required .GameState.MessageType type = 4;</code>
       */
      public Builder setType(com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .GameState.MessageType type = 4;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = com.example.dipoareoye.bluetoothframework.proto.GameStateProto.GameState.MessageType.PUCK;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GameState)
    }

    static {
      defaultInstance = new GameState(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GameState)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GameState_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GameState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n<com/example/dipoareoye/bluetoothframew" +
      "ork/proto/hockey.proto\"\205\001\n\tGameState\022\014\n\004" +
      "posX\030\001 \001(\005\022\017\n\007VectorX\030\002 \001(\005\022\017\n\007VectorY\030\003" +
      " \001(\005\022$\n\004type\030\004 \002(\0162\026.GameState.MessageTy" +
      "pe\"\"\n\013MessageType\022\010\n\004PUCK\020\000\022\t\n\005SCORE\020\001BA" +
      "\n/com.example.dipoareoye.bluetoothframew" +
      "ork.protoB\016GameStateProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GameState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GameState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GameState_descriptor,
        new java.lang.String[] { "PosX", "VectorX", "VectorY", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
